### PR TITLE
Fix signed distance function for 2D rectangle

### LINKED ISSUE #110: Own file for signed distance functions
The signed distance functions for implicit geometries are currently included in `utility_functions.hpp`. They should be moved to a separate file `signed_distance_functions.hpp`.

### PR DESCRIPTION
**Pull request by mschreter**
This PR includes:

- move distance functions to new file `distance_functions.hpp` (closes #110)
- bugfix in signed distance function for 2D rectangle
- add unit test for signed distance of rectangle

I just recognized that I should have split up this PR to be understable. The changes related to the bugfix have been made in the following lines:

https://github.com/MeltPoolDG/MeltPoolDG/blob/2f5f3a76862a2e757a2b301e1c73167063141182/include/meltpooldg/utilities/distance_functions.hpp#L328-L411

### CODE REVIEW

File: include/meltpooldg/utilities/distance_functions.hpp [hunk 1]
```diff
@@ -0,0 +1,434 @@
...
+            // point is outside of rectangle and above right of corner (3)
+            else if ((p[0] > corner[3][0]) && (p[1] > corner[3][1]))
+              return -std::min({-spherical_manifold(p, corner[3], 0.0),
+                                infinite_line<dim>(p, corner[2], corner[3])});
+            else if ((p[0] < corner[3][0]) && (p[1] < corner[3][1]))
+              return -std::min({-spherical_manifold(p, corner[3], 0.0),
+                                infinite_line<dim>(p, corner[3], corner[0])});
+            else
+              return spherical_manifold(p, corner[3], 0.0);
+          }
```
Comment (peterrum) [inline include/meltpooldg/utilities/distance_functions.hpp:410]: I must admit I have hard time to follow this code. For me this could be (your test also likes it!):
```suggestion
        if (lower_left_corner[0] <= p[0] && p[0] <= upper_right_corner[0] &&
            lower_left_corner[1] <= p[1] && p[1] <= upper_right_corner[1])
          // inside
          return std::min({p[0] - lower_left_corner[0],
                           upper_right_corner[0] - p[0],
                           p[1] - lower_left_corner[1],
                           upper_right_corner[1] - p[1]});
        else if (lower_left_corner[0] <= p[0] && p[0] <= upper_right_corner[0])
          // top or bottom
          return -std::min(std::abs(lower_left_corner[1] - p[1]),
                           std::abs(p[1] - upper_right_corner[1]));
        else if (lower_left_corner[1] <= p[1] && p[1] <= upper_right_corner[1])
          // left or right
          return -std::min(std::abs(lower_left_corner[0] - p[0]),
                           std::abs(p[0] - upper_right_corner[0]));
        else
          // corner
          return -std::min({p.distance(lower_left_corner),
                            p.distance(upper_right_corner),
                            p.distance(Point<2>(lower_left_corner[0], upper_right_corner[1])),
                            p.distance(Point<2>(upper_right_corner[0], lower_left_corner[1]))});
```

**Review by peterrum — COMMENTED** [review]
Overall looks good. I think the fixed function is a bit too complicated; I have posted an alternative. Maybe you could reduce the size of the mesh in 3D. In debug mode, it takes quite some time.

**Review by peterrum — APPROVED** [review]
