### PR TITLE
Fix test infrastructure

### LINKED ISSUE #116: Fix test infrastructure
@peterrum: FYI, feel free to add

- [ ] formatting -- would it make sense to use [fmt](https://github.com/fmtlib/fmt) (when `std::format` is introduced we could simply replace `fmt::format` through `std::format`
- [x] verbosity level 0 = minimal output for testing
- [x] move number of iterations of linear solvers to verbosity level 1
- [x] remove newton residual evolution from level 0
- [x] replace `l2_norm()` through `compute_stable_l2_norm()` 
- [x] adaflo: set verbosity in json-file to 0
- [ ] move number of dofs in case of AMR to level 1
- [ ] introduce timing in level 2
- [ ] debug vs. release
- [x] curvature: cut norm dependent on fraction of domain size

- [ ] introduce folder for tests "not_robust" that is not picked
- [ ] reduce linear solver tolerance to a "human" value
- [x] fix evaporation
- [x] test rounded geometry dependent normal tolerance
- [x] activate normal vector again

### PR DESCRIPTION
**Pull request by mschreter**
@peterrum: FYI, preparations for tomorrow

Closes #116

### CODE REVIEW

File: include/meltpooldg/interface/scratch_data.hpp [hunk 1]
```diff
@@ -45,14 +46,21 @@ namespace MeltPoolDG
...
+        this->pcout.push_back(
+          ConditionalOStream(std::cout,
+                             (Utilities::MPI::this_mpi_process(MPI_COMM_WORLD)) == 0 &&
+                               (i <= max_verbosity_level)));
+    }
 
     ScratchData(const ScratchData &scratch_data)
     {
       //@todo: check if mapping is deleted
-      this->do_matrix_free = scratch_data.do_matrix_free;
```
Comment (mschreter) [inline include/meltpooldg/interface/scratch_data.hpp:55]: TODO

**Comment by peterrum** [comment]
```diff
diff --git a/include/meltpooldg/curvature/curvature_operation.hpp b/include/meltpooldg/curvature/curvature_operation.hpp
index 1dff433..813b4ea 100644
--- a/include/meltpooldg/curvature/curvature_operation.hpp
+++ b/include/meltpooldg/curvature/curvature_operation.hpp
@@ -119,7 +119,7 @@ namespace MeltPoolDG
               << VectorTools::compute_L2_norm<dim>(solution_curvature,
                                                    *scratch_data,
                                                    curv_dof_idx,
-                                                   curv_quad_idx);
+                                                   curv_quad_idx) << " ";
         pcout << std::endl;
       }
 
diff --git a/include/meltpooldg/curvature/curvature_operation_adaflo_wrapper.hpp b/include/meltpooldg/curvature/curvature_operation_adaflo_wrapper.hpp
index c3a49ad..e9bfd93 100644
--- a/include/meltpooldg/curvature/curvature_operation_adaflo_wrapper.hpp
+++ b/include/meltpooldg/curvature/curvature_operation_adaflo_wrapper.hpp
@@ -143,7 +143,7 @@ namespace MeltPoolDG
           true); // @todo: adaflo does not use the boolean function argument
 
         scratch_data.get_pcout()
-          << " |k|=" << std::setw(15) << std::setprecision(10) << std::left
+          << " |k| = " << std::setw(15) << std::setprecision(10) << std::left
           << VectorTools::compute_L2_norm<dim>(get_curvature(),
                                                scratch_data,
                                                curv_adaflo_params.dof_index_curvature,
diff --git a/include/meltpooldg/normal_vector/normal_vector_operation.hpp b/include/meltpooldg/normal_vector/normal_vector_operation.hpp
index 4ffe7e3..96372a2 100644
--- a/include/meltpooldg/normal_vector/normal_vector_operation.hpp
+++ b/include/meltpooldg/normal_vector/normal_vector_operation.hpp
@@ -128,7 +128,7 @@ namespace MeltPoolDG
                 << VectorTools::compute_L2_norm<dim>(solution_normal_vector.block(d),
                                                      *scratch_data,
                                                      normal_dof_idx,
-                                                     normal_quad_idx);
+                                                     normal_quad_idx) << " ";
         pcout << std::endl;
       }
 
diff --git a/include/meltpooldg/normal_vector/normal_vector_operation_adaflo_wrapper.hpp b/include/meltpooldg/normal_vector/normal_vector_operation_adaflo_wrapper.hpp
index 18933c8..2a4d2f0 100644
--- a/include/meltpooldg/normal_vector/normal_vector_operation_adaflo_wrapper.hpp
+++ b/include/meltpooldg/normal_vector/normal_vector_operation_adaflo_wrapper.hpp
@@ -131,11 +131,11 @@ namespace MeltPoolDG
 
         for (unsigned int d = 0; d < dim; ++d)
           scratch_data.get_pcout()
-            << " |n|_" << d << "=" << std::setw(15) << std::setprecision(10) << std::left
+            << " |n|_" << d << " = " << std::setw(15) << std::setprecision(10) << std::left
             << VectorTools::compute_L2_norm<dim>(get_solution_normal_vector().block(d),
                                                  scratch_data,
                                                  normal_vec_adaflo_params.dof_index_normal,
-                                                 normal_vec_adaflo_params.quad_index);
+                                                 normal_vec_adaflo_params.quad_index) << " ";
 
         scratch_data.get_pcout() << std::endl;
       }

```

File: include/meltpooldg/interface/scratch_data.hpp (hunk 1 above)
Comment (mschreter) [reply include/meltpooldg/interface/scratch_data.hpp:55]: done

File: include/meltpooldg/reinitialization/reinitialization_operation_adaflo_wrapper.hpp [hunk 2]
```diff
@@ -87,7 +87,7 @@ namespace MeltPoolDG
           increment,
           level_set,
           rhs,
-          scratch_data.get_pcout(reinit_dof_idx),
+          scratch_data.get_pcout(),
```
Comment (peterrum) [inline include/meltpooldg/reinitialization/reinitialization_operation_adaflo_wrapper.hpp:90]: This is problematic (seg fault), since the class expects a reference.

Comment (mschreter) [reply include/meltpooldg/reinitialization/reinitialization_operation_adaflo_wrapper.hpp:90]: Thx for the hint. I'll fix this.

File: include/meltpooldg/interface/scratch_data.hpp [hunk 3]
```diff
@@ -45,14 +46,23 @@ namespace MeltPoolDG
...
+    ScratchData(const unsigned int max_verbosity_level = 0, const bool do_matrix_free = true)
       : do_matrix_free(do_matrix_free)
-    {}
+    {
+      this->pcout.clear();
+
+      for (unsigned int i = 0; i <= 10; ++i)
+        this->pcout.push_back(
+          ConditionalOStream(std::cout,
+                             (Utilities::MPI::this_mpi_process(MPI_COMM_WORLD)) == 0 &&
```
Comment (peterrum) [inline include/meltpooldg/interface/scratch_data.hpp:57]: TOOD. I guess we could pass in the constructor the MPI communicator?

File: include/meltpooldg/reinitialization/reinitialization_operation.hpp [hunk 4]
```diff
@@ -158,7 +158,7 @@ namespace MeltPoolDG
             src_rhs.copy_locally_owned_data_from(solution_level_set);
             src_rhs.update_ghost_values();
             reinit_operator->create_rhs(rhs, src_rhs);
-            iter = LinearSolve<VectorType, SolverCG<VectorType>, OperatorBase<double>>::solve(
+            iter = LinearSolve<VectorType, SolverGMRES<VectorType>, OperatorBase<double>>::solve(
```
Comment (peterrum) [inline include/meltpooldg/reinitialization/reinitialization_operation.hpp:161]: Why did you change the solver?

File: include/meltpooldg/utilities/linearsolve.hpp [hunk 5]
```diff
@@ -29,12 +29,13 @@ namespace MeltPoolDG
     solve(const OperatorType &      system_matrix,
           VectorType &              solution,
           const VectorType &        rhs,
-          const double              rel_tolerance_rhs = 1e-8,
+          const double              rel_tolerance_rhs = 1e-12,
```
Comment (peterrum) [inline include/meltpooldg/utilities/linearsolve.hpp:32]: This is not related to rhs anymore!?

File: include/meltpooldg/utilities/utilityfunctions.hpp [hunk 6]
```diff
@@ -748,5 +748,16 @@ namespace MeltPoolDG
         return 0.0;
       }
     } // namespace DistanceFunctions
-  }   // namespace UtilityFunctions
+      // return the exponent to the power of ten of an expression like 5*10^5 --> return 5
```
Comment (peterrum) [inline include/meltpooldg/utilities/utilityfunctions.hpp:751]: new line

**Review by peterrum — APPROVED** [review]
Very nice progress, Magdalena! I think the time invested here was worth it!

I have some small questions and remarks. Nevertheless, I will merge so that we can proceed on the other fronts! In the the middle term, I would suggest to use TravisCI for running the tests (my experience - in hyper.deal -  is that it is a bit faster than GitHub action).


Let me shortly summarize the changes made:
- an *output verbosity level* has been introduced, which can be set in the parameter file
- `MeltPoolDG::ConditionalOStream`s of the right verbosity can be queried via `ScratchData::get_pcout(level)`
- `MeltPoolDG::ConditionalOStream` adds a functionality to `dealii::ConditionalOStream` which reverts any modifications to the stream (like formatting, precision), once it is destructed
- verbosity level 0 is output that is printed always; higher verbosity level contains additional information (number of nonlinear/linear iterations, ...), which might be sensitive to the used hardware/configuration
- we use verbosity level 0 in the tests
- l2-norms have been replaced by L2-norm (see also `VectorTools::compute_L2_norm`) to make tests more robust in the case that there are small deviations in the adaptive refinement
- the function call `parallel::distributed::GridRefinement::refine_and_coarsen_fixed_fraction()` has been replace by `refine_and_coarsen_fixed_number()` since the latter function seems to more deterministic
- a tolerance is given to the function `MeltPoolDG::VectorTools::normalize()`, since its evaluation does only make sense close to the interface
- the (relative) tolerance required from the linear solver has been decreased from 1e-8 to 1e-12 to be able to reach the relative tolerance of 1e-8 required by deal.II (in production codes this value can be probably decreased significantly)
 - for tests that are sill not robust, there is a new folder `tests/tests_not_robust/` (currently 3 tests: recoil_pressure_amr.json, recoil_pressure_fixed_solid_domain.json, rising_bubble_amr_mf_adaflo.json)

File: include/meltpooldg/reinitialization/reinitialization_operation.hpp (hunk 4 above)
Comment (mschreter) [reply include/meltpooldg/reinitialization/reinitialization_operation.hpp:161]: I cannot remember :/. CG would be fine as well. I would shift this to a TODO.

File: include/meltpooldg/utilities/linearsolve.hpp (hunk 5 above)
Comment (mschreter) [reply include/meltpooldg/utilities/linearsolve.hpp:32]: True. TODO as well.

**Comment by mschreter** [comment]
> Very nice progress, Magdalena! I think the time invested here was worth it!
> 
> I have some small questions and remarks. Nevertheless, I will merge so that we can proceed on the other fronts! In the the middle term, I would suggest to use TravisCI for running the tests (my experience - in hyper.deal - is that it is a bit faster than GitHub action).
> 
> Let me shortly summarize the changes made:
> 
> * an _output verbosity level_ has been introduced, which can be set in the parameter file
> * `MeltPoolDG::ConditionalOStream`s of the right verbosity can be queried via `ScratchData::get_pcout(level)`
> * `MeltPoolDG::ConditionalOStream` adds a functionality to `dealii::ConditionalOStream` which reverts any modifications to the stream (like formatting, precision), once it is destructed
> * verbosity level 0 is output that is printed always; higher verbosity level contains additional information (number of nonlinear/linear iterations, ...), which might be sensitive to the used hardware/configuration
> * we use verbosity level 0 in the tests
> * l2-norms have been replaced by L2-norm (see also `VectorTools::compute_L2_norm`) to make tests more robust in the case that there are small deviations in the adaptive refinement
> * the function call `parallel::distributed::GridRefinement::refine_and_coarsen_fixed_fraction()` has been replace by `refine_and_coarsen_fixed_number()` since the latter function seems to more deterministic
> * a tolerance is given to the function `MeltPoolDG::VectorTools::normalize()`, since its evaluation does only make sense close to the interface
> * the (relative) tolerance required from the linear solver has been decreased from 1e-8 to 1e-12 to be able to reach the relative tolerance of 1e-8 required by deal.II (in production codes this value can be probably decreased significantly)
> * for tests that are sill not robust, there is a new folder `tests/tests_not_robust/` (currently 3 tests: recoil_pressure_amr.json, recoil_pressure_fixed_solid_domain.json, rising_bubble_amr_mf_adaflo.json)

... @nmuch: Peter's comment might be also relevant for you and renders some aspects for the implementation of robust tests in the future :-).
